# Definimos la imagen de Docker con Python
image: python:3.9

# Definimos las etapas
stages:
  - test

# Configuración del Job de pruebas
run_tests:
  stage: test
  rules:
    # Esta regla indica que el job solo se cree si el evento es un Merge Request
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  before_script:
    - apt-get update && apt-get install -y build-essential libsnmp-dev
    - make install_dependencias_ci
  script:
    - pytest  # Ejecuta los tests