# Definimos la imagen de Docker con Python
image: python:3.9

# Definimos las etapas
stages:
  - test

# Configuración del Job de pruebas
run_tests:
  stage: test
  before_script:
    - make install_dependencias_ci
  script:
    - pytest  # Ejecuta los tests